// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/mock.go
//

// Package mock_core is a generated GoMock package.
package mock_core

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	core "yadro.com/course/search/core"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// GetComicsIdsByWords mocks base method.
func (m *MockDB) GetComicsIdsByWords(ctx context.Context, words []string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicsIdsByWords", ctx, words)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicsIdsByWords indicates an expected call of GetComicsIdsByWords.
func (mr *MockDBMockRecorder) GetComicsIdsByWords(ctx, words any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicsIdsByWords", reflect.TypeOf((*MockDB)(nil).GetComicsIdsByWords), ctx, words)
}

// GetComicsesInfoByIds mocks base method.
func (m *MockDB) GetComicsesInfoByIds(ctx context.Context, ids []int) ([]core.ComicsInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicsesInfoByIds", ctx, ids)
	ret0, _ := ret[0].([]core.ComicsInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicsesInfoByIds indicates an expected call of GetComicsesInfoByIds.
func (mr *MockDBMockRecorder) GetComicsesInfoByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicsesInfoByIds", reflect.TypeOf((*MockDB)(nil).GetComicsesInfoByIds), ctx, ids)
}

// GetWords2Ids mocks base method.
func (m *MockDB) GetWords2Ids(ctx context.Context) (map[string]*[]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWords2Ids", ctx)
	ret0, _ := ret[0].(map[string]*[]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWords2Ids indicates an expected call of GetWords2Ids.
func (mr *MockDBMockRecorder) GetWords2Ids(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWords2Ids", reflect.TypeOf((*MockDB)(nil).GetWords2Ids), ctx)
}

// MockIndex is a mock of Index interface.
type MockIndex struct {
	ctrl     *gomock.Controller
	recorder *MockIndexMockRecorder
	isgomock struct{}
}

// MockIndexMockRecorder is the mock recorder for MockIndex.
type MockIndexMockRecorder struct {
	mock *MockIndex
}

// NewMockIndex creates a new mock instance.
func NewMockIndex(ctrl *gomock.Controller) *MockIndex {
	mock := &MockIndex{ctrl: ctrl}
	mock.recorder = &MockIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndex) EXPECT() *MockIndexMockRecorder {
	return m.recorder
}

// GetComicsIdsByWords mocks base method.
func (m *MockIndex) GetComicsIdsByWords(ctx context.Context, words []string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComicsIdsByWords", ctx, words)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComicsIdsByWords indicates an expected call of GetComicsIdsByWords.
func (mr *MockIndexMockRecorder) GetComicsIdsByWords(ctx, words any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComicsIdsByWords", reflect.TypeOf((*MockIndex)(nil).GetComicsIdsByWords), ctx, words)
}

// Update mocks base method.
func (m *MockIndex) Update(newVals map[string]*[]int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", newVals)
}

// Update indicates an expected call of Update.
func (mr *MockIndexMockRecorder) Update(newVals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIndex)(nil).Update), newVals)
}

// MockWords is a mock of Words interface.
type MockWords struct {
	ctrl     *gomock.Controller
	recorder *MockWordsMockRecorder
	isgomock struct{}
}

// MockWordsMockRecorder is the mock recorder for MockWords.
type MockWordsMockRecorder struct {
	mock *MockWords
}

// NewMockWords creates a new mock instance.
func NewMockWords(ctrl *gomock.Controller) *MockWords {
	mock := &MockWords{ctrl: ctrl}
	mock.recorder = &MockWordsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWords) EXPECT() *MockWordsMockRecorder {
	return m.recorder
}

// Norm mocks base method.
func (m *MockWords) Norm(ctx context.Context, phrase string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Norm", ctx, phrase)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Norm indicates an expected call of Norm.
func (mr *MockWordsMockRecorder) Norm(ctx, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Norm", reflect.TypeOf((*MockWords)(nil).Norm), ctx, phrase)
}

// MockSearcher is a mock of Searcher interface.
type MockSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockSearcherMockRecorder
	isgomock struct{}
}

// MockSearcherMockRecorder is the mock recorder for MockSearcher.
type MockSearcherMockRecorder struct {
	mock *MockSearcher
}

// NewMockSearcher creates a new mock instance.
func NewMockSearcher(ctrl *gomock.Controller) *MockSearcher {
	mock := &MockSearcher{ctrl: ctrl}
	mock.recorder = &MockSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearcher) EXPECT() *MockSearcherMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSearcher) Search(ctx context.Context, limit int, phrase string) ([]core.Comics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, limit, phrase)
	ret0, _ := ret[0].([]core.Comics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearcherMockRecorder) Search(ctx, limit, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearcher)(nil).Search), ctx, limit, phrase)
}

// SearchIndex mocks base method.
func (m *MockSearcher) SearchIndex(ctx context.Context, limit int, phrase string) ([]core.Comics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchIndex", ctx, limit, phrase)
	ret0, _ := ret[0].([]core.Comics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchIndex indicates an expected call of SearchIndex.
func (mr *MockSearcherMockRecorder) SearchIndex(ctx, limit, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchIndex", reflect.TypeOf((*MockSearcher)(nil).SearchIndex), ctx, limit, phrase)
}

// SubscribeInitiatorIndexUpdate mocks base method.
func (m *MockSearcher) SubscribeInitiatorIndexUpdate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubscribeInitiatorIndexUpdate")
}

// SubscribeInitiatorIndexUpdate indicates an expected call of SubscribeInitiatorIndexUpdate.
func (mr *MockSearcherMockRecorder) SubscribeInitiatorIndexUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeInitiatorIndexUpdate", reflect.TypeOf((*MockSearcher)(nil).SubscribeInitiatorIndexUpdate))
}

// SubscribeOnUpdateIndex mocks base method.
func (m *MockSearcher) SubscribeOnUpdateIndex(updateEventName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOnUpdateIndex", updateEventName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeOnUpdateIndex indicates an expected call of SubscribeOnUpdateIndex.
func (mr *MockSearcherMockRecorder) SubscribeOnUpdateIndex(updateEventName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOnUpdateIndex", reflect.TypeOf((*MockSearcher)(nil).SubscribeOnUpdateIndex), updateEventName)
}

// UpdateIndex mocks base method.
func (m *MockSearcher) UpdateIndex() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateIndex")
}

// UpdateIndex indicates an expected call of UpdateIndex.
func (mr *MockSearcherMockRecorder) UpdateIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIndex", reflect.TypeOf((*MockSearcher)(nil).UpdateIndex))
}

// MockInitiator is a mock of Initiator interface.
type MockInitiator struct {
	ctrl     *gomock.Controller
	recorder *MockInitiatorMockRecorder
	isgomock struct{}
}

// MockInitiatorMockRecorder is the mock recorder for MockInitiator.
type MockInitiatorMockRecorder struct {
	mock *MockInitiator
}

// NewMockInitiator creates a new mock instance.
func NewMockInitiator(ctrl *gomock.Controller) *MockInitiator {
	mock := &MockInitiator{ctrl: ctrl}
	mock.recorder = &MockInitiatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInitiator) EXPECT() *MockInitiatorMockRecorder {
	return m.recorder
}

// UpdateIndex mocks base method.
func (m *MockInitiator) UpdateIndex(searcher core.Searcher) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateIndex", searcher)
}

// UpdateIndex indicates an expected call of UpdateIndex.
func (mr *MockInitiatorMockRecorder) UpdateIndex(searcher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIndex", reflect.TypeOf((*MockInitiator)(nil).UpdateIndex), searcher)
}

// MockUpdateSubscriber is a mock of UpdateSubscriber interface.
type MockUpdateSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateSubscriberMockRecorder
	isgomock struct{}
}

// MockUpdateSubscriberMockRecorder is the mock recorder for MockUpdateSubscriber.
type MockUpdateSubscriberMockRecorder struct {
	mock *MockUpdateSubscriber
}

// NewMockUpdateSubscriber creates a new mock instance.
func NewMockUpdateSubscriber(ctrl *gomock.Controller) *MockUpdateSubscriber {
	mock := &MockUpdateSubscriber{ctrl: ctrl}
	mock.recorder = &MockUpdateSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateSubscriber) EXPECT() *MockUpdateSubscriberMockRecorder {
	return m.recorder
}

// SubscribeUpdateEvent mocks base method.
func (m *MockUpdateSubscriber) SubscribeUpdateEvent(updateEventName string, searcher core.Searcher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeUpdateEvent", updateEventName, searcher)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeUpdateEvent indicates an expected call of SubscribeUpdateEvent.
func (mr *MockUpdateSubscriberMockRecorder) SubscribeUpdateEvent(updateEventName, searcher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeUpdateEvent", reflect.TypeOf((*MockUpdateSubscriber)(nil).SubscribeUpdateEvent), updateEventName, searcher)
}
