// Code generated by MockGen. DO NOT EDIT.
// Source: search_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=search_grpc.pb.go -destination=mocks/mock.go
//

// Package mock_search is a generated GoMock package.
package mock_search

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	search "yadro.com/course/proto/search"
)

// MockSearchClient is a mock of SearchClient interface.
type MockSearchClient struct {
	ctrl     *gomock.Controller
	recorder *MockSearchClientMockRecorder
	isgomock struct{}
}

// MockSearchClientMockRecorder is the mock recorder for MockSearchClient.
type MockSearchClientMockRecorder struct {
	mock *MockSearchClient
}

// NewMockSearchClient creates a new mock instance.
func NewMockSearchClient(ctrl *gomock.Controller) *MockSearchClient {
	mock := &MockSearchClient{ctrl: ctrl}
	mock.recorder = &MockSearchClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchClient) EXPECT() *MockSearchClientMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockSearchClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Ping", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ping indicates an expected call of Ping.
func (mr *MockSearchClientMockRecorder) Ping(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSearchClient)(nil).Ping), varargs...)
}

// Search mocks base method.
func (m *MockSearchClient) Search(ctx context.Context, in *search.SearchRequest, opts ...grpc.CallOption) (*search.SearchReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Search", varargs...)
	ret0, _ := ret[0].(*search.SearchReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchClientMockRecorder) Search(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchClient)(nil).Search), varargs...)
}

// SearchIndex mocks base method.
func (m *MockSearchClient) SearchIndex(ctx context.Context, in *search.SearchRequest, opts ...grpc.CallOption) (*search.SearchReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchIndex", varargs...)
	ret0, _ := ret[0].(*search.SearchReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchIndex indicates an expected call of SearchIndex.
func (mr *MockSearchClientMockRecorder) SearchIndex(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchIndex", reflect.TypeOf((*MockSearchClient)(nil).SearchIndex), varargs...)
}

// SearchRandom mocks base method.
func (m *MockSearchClient) SearchRandom(ctx context.Context, in *search.SearchRandomRequest, opts ...grpc.CallOption) (*search.SearchReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchRandom", varargs...)
	ret0, _ := ret[0].(*search.SearchReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRandom indicates an expected call of SearchRandom.
func (mr *MockSearchClientMockRecorder) SearchRandom(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRandom", reflect.TypeOf((*MockSearchClient)(nil).SearchRandom), varargs...)
}

// MockSearchServer is a mock of SearchServer interface.
type MockSearchServer struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServerMockRecorder
	isgomock struct{}
}

// MockSearchServerMockRecorder is the mock recorder for MockSearchServer.
type MockSearchServerMockRecorder struct {
	mock *MockSearchServer
}

// NewMockSearchServer creates a new mock instance.
func NewMockSearchServer(ctrl *gomock.Controller) *MockSearchServer {
	mock := &MockSearchServer{ctrl: ctrl}
	mock.recorder = &MockSearchServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchServer) EXPECT() *MockSearchServerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockSearchServer) Ping(arg0 context.Context, arg1 *emptypb.Empty) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ping indicates an expected call of Ping.
func (mr *MockSearchServerMockRecorder) Ping(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSearchServer)(nil).Ping), arg0, arg1)
}

// Search mocks base method.
func (m *MockSearchServer) Search(arg0 context.Context, arg1 *search.SearchRequest) (*search.SearchReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].(*search.SearchReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchServerMockRecorder) Search(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchServer)(nil).Search), arg0, arg1)
}

// SearchIndex mocks base method.
func (m *MockSearchServer) SearchIndex(arg0 context.Context, arg1 *search.SearchRequest) (*search.SearchReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchIndex", arg0, arg1)
	ret0, _ := ret[0].(*search.SearchReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchIndex indicates an expected call of SearchIndex.
func (mr *MockSearchServerMockRecorder) SearchIndex(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchIndex", reflect.TypeOf((*MockSearchServer)(nil).SearchIndex), arg0, arg1)
}

// SearchRandom mocks base method.
func (m *MockSearchServer) SearchRandom(arg0 context.Context, arg1 *search.SearchRandomRequest) (*search.SearchReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRandom", arg0, arg1)
	ret0, _ := ret[0].(*search.SearchReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRandom indicates an expected call of SearchRandom.
func (mr *MockSearchServerMockRecorder) SearchRandom(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRandom", reflect.TypeOf((*MockSearchServer)(nil).SearchRandom), arg0, arg1)
}

// mustEmbedUnimplementedSearchServer mocks base method.
func (m *MockSearchServer) mustEmbedUnimplementedSearchServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSearchServer")
}

// mustEmbedUnimplementedSearchServer indicates an expected call of mustEmbedUnimplementedSearchServer.
func (mr *MockSearchServerMockRecorder) mustEmbedUnimplementedSearchServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSearchServer", reflect.TypeOf((*MockSearchServer)(nil).mustEmbedUnimplementedSearchServer))
}

// MockUnsafeSearchServer is a mock of UnsafeSearchServer interface.
type MockUnsafeSearchServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeSearchServerMockRecorder
	isgomock struct{}
}

// MockUnsafeSearchServerMockRecorder is the mock recorder for MockUnsafeSearchServer.
type MockUnsafeSearchServerMockRecorder struct {
	mock *MockUnsafeSearchServer
}

// NewMockUnsafeSearchServer creates a new mock instance.
func NewMockUnsafeSearchServer(ctrl *gomock.Controller) *MockUnsafeSearchServer {
	mock := &MockUnsafeSearchServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeSearchServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeSearchServer) EXPECT() *MockUnsafeSearchServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedSearchServer mocks base method.
func (m *MockUnsafeSearchServer) mustEmbedUnimplementedSearchServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSearchServer")
}

// mustEmbedUnimplementedSearchServer indicates an expected call of mustEmbedUnimplementedSearchServer.
func (mr *MockUnsafeSearchServerMockRecorder) mustEmbedUnimplementedSearchServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSearchServer", reflect.TypeOf((*MockUnsafeSearchServer)(nil).mustEmbedUnimplementedSearchServer))
}
